// lm-vue/src/components/grid/grid.vue
<template>
  <div class="lm-grids" :class="{
      'lm-grid-no-lr-borders': !showLrBorders,
      'lm-grid-no-borders': !showBorders
    }"
  >
    <slot></slot>
  </div>
</template>
<script>
export default {
  name: 'lm-grid',
  data () {
    return {
      childrenSize: 3
    }
  },
  methods: {
    /**
     * [countColumn 计算产生的cols列数]
     * @return {[type]} [description]
     */
    countColumn () {
      this.childrenSize = this.$children.length
      this.$children.forEach((c, index) => (c.index = index))
    }
  },
  props: {
    /**
     * [cols 列数]
     * @type {Object}
     */
    cols: Number,
    /**
     * [showLrBorders 是否显示左右边框  ]
     * @type {Object}
     */
    showLrBorders: {
      type: Boolean,
      default: true
    },
    /**
     * [showVerticalDividers 是否显示垂直分割线]
     * @type {Object}
     */
    showVerticalDividers: {
      type: Boolean,
      default: true
    },
    /**
     * [showBorders 是否显示所有边框]
     * @type {Object}
     */
    showBorders: {
      type: Boolean,
      default: true
    }
  },
  computed: {
    /**
     * [column 计算列数]
     * @return {[type]} [description]
     */
    column () {
      return this.cols || this.childrenSize;
    }
  }
}
</script>

// lm-react/src/components/grid/Grid.tsx
import React, { Children } from 'react';
import { Component, View, Transition, ComponentProps } from '@src/core';
import GridItem from './GridItem'
interface GridProps extends ComponentProps {
  cols?: number
  showLrBorders?: boolean
  showVerticalDividers?: boolean
  showBorders?: boolean
};

export default class Grid extends Component<GridProps, any> {
  static Item: any
  public wrap: any
  public childrenSize: number = 3;

  static defaultProps: GridProps = {
    cols: 3,
    showLrBorders: true,
    showVerticalDividers: true,
    showBorders: true
  }

  constructor(props: GridProps) {
    super(props);
  }

  render() {
    let { cols, children, showLrBorders, showBorders, showVerticalDividers } = this.props;
    if (children && children.length) this.childrenSize = children.length;
    let column = cols && this.childrenSize;
    let grids = []
    if (children && children.length !== 0) {
      for (let i = 0; i < children.length; i++) {
        grids.push(React.cloneElement(children[i], {
          key: i,
          parent: {
            index: i,
            column: column,
            showLrBorders: showLrBorders,
            showVerticalDividers: showVerticalDividers
          }
        }))
      }
    }
    return (
      <div className={this.classNames('lm-grids', {
        'lm-grid-no-lr-borders': !showLrBorders,
        'lm-grid-no-borders': !showBorders
      })}>
        {grids}
      </div>
    );
  };
};
