// lm-react/src/components/header/Header.tsx
import React, { Children } from 'react';
import { Component, View, Transition, ComponentProps } from '@src/core';
import { createHashHistory as createHistory } from "history";
// 创建历史对象
const history = createHistory();

// header 组件
interface LeftOptionsProps {
  showBack?: boolean
  preventGoBack?: boolean
  backText?: string
}
interface RightOptionsProps {
  showMore?: boolean
}
interface HeaderProps extends ComponentProps {
  leftOptions?: LeftOptionsProps
  title?: string
  transition?: string
  rightOptions?: RightOptionsProps
  position?: string
  left?: any
  right?: any
  overwriteLeft?: any
  overwriteTitle?: any
  onClickBack?: Function
  onClickMore?: Function
};

export default class Header extends Component<HeaderProps, any> {

  state = {
  }

  wrap: any

  static defaultProps: HeaderProps = {
    leftOptions: {
      showBack: true,
      preventGoBack: false,
      backText: ''
    },
    title: '',
    transition: 'lm',
    rightOptions: {
      showMore: false
    },
    position: 'static'
  }

  constructor(props: HeaderProps) {
    super(props);
  }

  get _leftOptions() {
    let { leftOptions } = this.props;
    return Object.assign({
      showBack: true,
      preventGoBack: false,
      backText: ''
    }, leftOptions || {})
  }

  onClickBack() {

    if (this._leftOptions.preventGoBack) {
      this.props.onClickBack && this.props.onClickBack()
    } else {
      history ? history.goBack() : window.history.back()
    }
  }
  onClickMore(event) {
    this.props.onClickMore && this.props.onClickMore()
    event.preventDefault();
  }
  render(): React.ReactElement<any> {
    let { children, title, transition, left, right, overwriteTitle, leftOptions, rightOptions, overwriteLeft, className } = this.props;

    return (
      <div className={this.className('lm-header', className)}>
        <div className="lm-header-left">
          {
            overwriteLeft ? overwriteLeft : (
              <React.Fragment>
                <Transition name={transition}>
                  <a style={this._leftOptions.showBack ? { 'display': 'none' } : { 'display': 'block' }} className="lm-header-back">{typeof this._leftOptions.backText === 'undefined' ? '返回' : this._leftOptions.backText}</a>
                </Transition>
                <Transition name={transition}>
                  <div style={this._leftOptions.showBack ? { 'display': 'none' } : { 'display': 'block' }} className="left-arrow" onClick={() => this.onClickBack()}></div>
                </Transition>
              </React.Fragment>
            )
          }
          {left}
        </div>
        {
          !overwriteTitle ? (
            <h1 className="lm-header-title">
              <Transition name={transition}>
                {title ? (<span>{title}</span>) : (<React.Fragment>{children}</React.Fragment>)}
              </Transition>
            </h1>
          ) : (
              <div className="lm-header-title-area">
                {overwriteTitle}
              </div>
            )
        }
        <div className="lm-header-right">
          {
            rightOptions.showMore ? (<a className="lm-header-more" onClick={(e) => this.onClickMore(e)}></a>) : (null)
          }
          {right}
        </div>
      </div>
    );
  };
};

// lm-vue/src/components/header/header.vue
<template>
  <div class="lm-header">
    <div class="lm-header-left">
      <slot name="overwrite-left">
        <transition :name="transition">
          <a class="lm-header-back" v-show="_leftOptions.showBack" @click.prevent.self="onClickBack">{{ typeof _leftOptions.backText === 'undefined' ? '返回' : _leftOptions.backText}}</a>
        </transition>
        <transition :name="transition">
          <div class="left-arrow" @click="onClickBack" v-show="_leftOptions.showBack"></div>
        </transition>
      </slot>
      <slot name="left"></slot>
    </div>
    <h1 class="lm-header-title" @click="$emit('on-click-title')" v-if="!shouldOverWriteTitle">
      <slot>
        <transition :name="transition">
          <span v-show="title">{{title}}</span>
        </transition>
      </slot>
    </h1>
    <div class="lm-header-title-area" v-if="shouldOverWriteTitle">
      <slot name="overwrite-title"></slot>
    </div>
    <div class="lm-header-right">
      <a class="lm-header-more" @click.prevent.self="$emit('on-click-more')" v-if="rightOptions.showMore"></a>
      <slot name="right"></slot>
    </div>
  </div>
</template>

<script>
import { extend } from '@/utils/tools'
export default {
  name: 'lm-header',
  props: {
    /**
     * [leftOptions 左侧返回按钮]
     * @type {[type]}
     */
    leftOptions: Object,
    /**
     * [title 文字标题]
     * @type {[type]}
     */
    title: String,
    /**
     * [transition 运动形式名字]
     * @type {[type]}
     */
    transition: String,
    /**
     * [rightOptions 右侧更多操作]
     * @type {Object}
     */
    rightOptions: {
      type: Object,
      default () {
        return {
          showMore: false
        }
      }
    },
    /**
     * [position top|bottom|static]
     * @type {Object}
     */
    position: {
      type: String,
      ddefault: 'static'
    }
  },
  beforeMount () {
    if (this.$slots['overwrite-title']) {
      this.shouldOverWriteTitle = true
    }
  },
  computed: {
    getHeaderStyle () {
      let style = {};
      if (this.position !== 'static') {
        style[this.position] = 0;
      }
      return style;
    },
    /**
     * [_leftOptions 计算左侧按钮部分属性]
     * @return {[type]} [description]
     */
    _leftOptions () {
      return extend({
        showBack: true,
        preventGoBack: false,
        backText: ''
      }, this.leftOptions || {})
    }
  },
  methods: {
    /**
     * [onClickBack 点击返回操作]
     * @return {[type]} [description]
     */
    onClickBack () {
      if (this._leftOptions.preventGoBack) {
        this.$emit('on-click-back')
      } else {
        this.$router ? this.$router.back() : window.history.back()
      }
    }
  },
  data () {
    return {
      shouldOverWriteTitle: false
    }
  }
}
</script>
