// lm-react/examples/views/PopupPicker.tsx
import React from 'react';
import ReactDom from 'react-dom';
import { Component, ComponentProps } from '@src/core'
import { Page, Header, TransferDom, Group, PopupPicker, Popup, PopupHeader } from '@src/index'
//初始化页面
import china_address from './china_address_v4'

interface PopupPickerProps extends ComponentProps {

}

export default class PopupPickerPage extends Component<PopupPickerProps, any> {
  constructor(props: PopupPickerProps) {
    super(props);
  }

  state = {
    value: false,
    value1: ['iPhone'],
    addressData: china_address,
    address: ['150000', '150100', '150102'],
    list1: [
      ['小米', 'iPhone', '华为', '情怀', '三星', '其他', '不告诉你'],
      ['小米1', 'iPhone2', '华为3', '情怀4', '三星5', '其他6', '不告诉你7']
    ]
  }
  clickHandle() {

  }
  onClickRight() {
    this.setState({
      value: false
    })
  }
  render() {
    let { value, list1, value1, addressData, address } = this.state;
    let leftOptions = {
      showBack: false
    }
    return (
      <Page header={<Header leftOptions={leftOptions} className={'lm-header-fixed'}>popup-picker</Header>}>
        <Group>
          <PopupPicker data={list1} value={value1} label={'popup-picker'}></PopupPicker>
        </Group>
      </Page>
    );
  }
}

// lm-angular/examples/app/views/popup-picker/popup-picker.component.ts
import { Component,ChangeDetectorRef } from '@angular/core';

import china_address from '../../../../src/components/address/china_address_v4'

@Component({
  selector: 'popup-picker-page',
  templateUrl: './popup-picker.component.html',
  styleUrls: ['./popup-picker.component.scss']
})
export class PopupPickerComponent {
  title = 'lm-angular-demo'
  title1: string = '手机机型'
  value1: any[] = ['iPhone']
  test1: any[] = ['双向绑定1','双向绑定2']
  test2: any[] = ['单向绑定1','单向绑定2' ]
  test3: any[] = [{value: '单双向绑定1'},{value: '单双向绑定2'}]
  
  value: any[] = ['150000','150100','150102']
  addressData: any = china_address
  showAddress: boolean = false
  index: number = 1
  clickHandle() {
    this.index = this.index+1;
    let test1 = this.test1;
    let test2 = this.test2;
    test1[0] = `双向绑定${ this.index }`
    this.test1 = JSON.parse(JSON.stringify(test1));
    test2[0] = `单向绑定${ this.index }`
    this.test2 = JSON.parse(JSON.stringify(test2));
    this.test3[0].value = `单双向绑定${ this.index }`
    this.cdr.detectChanges();
    this.cdr.markForCheck();
  }
  show() {
    console.log('show')
  }
  hide() {
    console.log('hide')
  }
   constructor(
    private cdr: ChangeDetectorRef) {
  } 
  shadowChange(value) {
    console.log(value, 'shadowChange')
  }
  logHide (str) {
    console.log('on-hide', str)
  }
  logShow (str) {
    console.log('on-show')
  }
  onShadowChange2 (ids, names) {
    console.log(ids, names)
  }
 
  change (value) {
    console.log('change', value)
  }
  onChange (val) {
    console.log('change', val)
  }
  log (str1, str2 = '') {
    console.log(str1, str2)
  }
  
  list1:any[] = [['小米', 'iPhone', '华为', '情怀', '三星', '其他', '不告诉你'], ['小米1', 'iPhone2', '华为3', '情怀4', '三星5', '其他6', '不告诉你7']]
}

<lm-template>
  <ng-template #header>
  	<lm-header  class="lm-header-fixed" [left-options]="{ showBack: false }" [right-options]="{ showMore: false }">
  	  <ng-template #navbarTitle>{{ title }}</ng-template>
  	  <ng-template #navbarRight>
  	  	<div (click)="onClickMoreHandle()">right</div>
  	  </ng-template>	
  	</lm-header>
  </ng-template>
  
  <lm-group>
    <lm-popup-picker 
     [label]="title1" 
     [data]="list1"
     [(ngModel)]="value1" 
     [placeholder]="'请选择'"
     (on-show)="show($event)"
     (on-hide)="hide($event)"
     (on-change)="change($event)"
     (on-shadow-change)="shadowChange($event)"></lm-popup-picker>
    <lm-address 
      (on-hide)="logHide($event)"
      (on-show)="logShow($event)"
      [label]="'地址选择'"
      [model]="value"
      [data]="addressData"
      [show]="showAddress"
      (on-shadow-change)="onShadowChange2($event)"
      placeholder="请选择地址"
    ></lm-address> 
  </lm-group>
  {{ test1 }}
  <div class="" style="width: 1rem; height: 1rem;background: red;" (click)="clickHandle($event)">点击</div>
  {{ test2 }}
  <!-- <lm-demo [(ngModel)]="test1"></lm-demo> -->
  <lm-demo [model]="test2"></lm-demo>
  <!-- <lm-demo [(ngModel)]="test3"></lm-demo> -->
</lm-template>
