// lm-angular/examples/app/views/dialog/dialog.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'dialog-page',
  templateUrl: './dialog.component.html',
  styleUrls: ['./dialog.component.scss']
})
export class DialogComponent {
  title = 'lm-angular-demo';
  switchState: Boolean = false
  onClickMoreHandle () {
  	console.log('onClickMoreHandle')
  }
  onSwitchChangeHandle (value) {
    this.switchState = value;
  }
  closeHandle () {
    this.switchState = false;
  }
  fours: any[] = []
  items: any[] = [
    {
      link: 'grid',
      label: 'grid'
    }
  ]
}

<lm-template>
  <ng-template #header>
  	<lm-header  class="lm-header-fixed" [left-options]="{ showBack: false }" [right-options]="{ showMore: false }">
  	  <ng-template #navbarTitle>{{ title }}</ng-template>
  	  <ng-template #navbarRight>
  	  	<div (click)="onClickMoreHandle()">right</div>
  	  </ng-template>	
  	</lm-header>
  </ng-template>
  
  <lm-group>
    <lm-switch [label]="'switch'" [(ngModel)]="switchState"></lm-switch>
    <lm-switch [label]="'switch'" [(ngModel)]="switchState"></lm-switch>

    <div *transfer-dom="true">
      <lm-dialog [(ngModel)]="switchState" class="dialog-demo">
        <div class="img-box">
          <img src="https://ws1.sinaimg.cn/large/663d3650gy1fq6824ur1dj20ia0pydlm.jpg" style="max-width:100%">
        </div>
        <div (click)="closeHandle()">
          <span class="lm-close"></span>
        </div>
      </lm-dialog>
    </div>
  </lm-group>

</lm-template>

// lm-react/examples/views/Dialog.tsx
import React from 'react';
import ReactDom from 'react-dom';
import { Component, ComponentProps } from '@src/core'
import { Page, Header, Group, Scroll, Dialog, TransferDom } from '@src/index'
//初始化页面

interface DialogProps extends ComponentProps {
  match: object
  location: object
  history: object
}

export default class DialogPage extends Component<DialogProps, any> {
  constructor(props: DialogProps) {
    super(props);
  }
  onChange(value) {
    this.setState({
      value: value
    })
  }
  state = {
    value: false
  }
  render() {
    let leftOptions = {
      showBack: false
    }
    let { value } = this.state
    let buttton = {
      width: '1rem',
      height: '1rem',
      background: 'red'
    }
    return (
      <Page
        header={<Header leftOptions={leftOptions} className={'lm-header-fixed'}>Dialog</Header>}>
        <Scroll>

          <Group header={<Group.Title>Dialog</Group.Title>}>
            <Group.Switch value={value} onChange={(e) => this.onChange(e)} switchLabel={'Dialog'}></Group.Switch>
          </Group>
          <TransferDom>
            <Dialog visible={value}>
              <div className="img-box">
                <img src="https://ws1.sinaimg.cn/large/663d3650gy1fq6824ur1dj20ia0pydlm.jpg"
                  style={{
                    'maxWidth': '100%'
                  }} alt="" />
              </div>
              <div onClick={() => this.onChange(false)}>
                <span className="lm-close"></span>
              </div>
            </Dialog>
          </TransferDom>
        </Scroll>
      </Page>
    );
  }
}
