// lm-vue/src/components/switch/switch.vue
<template>
  <div class="lm-switch-wrapper lm-cell lm-cell-switch">
    <div class="lm-cell-bd">
      <label class="lm-label" :style="labelStyle" :class="labelClass" v-html="label"></label>
      <inline-desc v-if="inlineDesc">{{ inlineDesc }}</inline-desc>
    </div>
    <div class="lm-cell-switch-body">
      <input class="lm-switch" type="checkbox" :disabled="disabled" v-model="currentValue" />
      <div v-if="preventDefault" class="lm-switch-overlay" @click="onClick"></div>
    </div>
  </div>
</template>

<script>
import InlineDesc from '../inline-desc/inline-desc'
import { cleanStyle } from '@/utils'
export default {
  name: 'lm-switch',
  props: {
    label: {
      type: String,
      required: true
    },
    disabled: Boolean,
    value: {
      type: [Boolean, String, Number],
      default: false,
      required: true
    },
    inlineDesc: [String, Boolean, Number],
    preventDefault: Boolean,
    valueMap: {
      type: Array,
      default: () => ([false, true])
    }
  },
  computed: {
    parent () {
      const { $parent } = this
      return $parent || {}
    },
    labelStyle () {
      let isHTML = /<\/?[^>]*>/.test(this.label)
      let width = Math.min(isHTML ? 5 : (this.label.length + 1), 14) + 'em'
      return cleanStyle({
        display: 'block',
        width: this.parent.labelWidth || width,
        textAlign: this.parent.labelAlign
      })
    },
    labelClass () {
      return {
        'lm-cell-justify': this.parent.labelAlign === 'justify'
      }
    }
  },
  components: {
    InlineDesc
  },
  methods: {
    /**
     * [onClick 点击事件]
     * @return {[type]} [description]
     */
    onClick () {
      this.$emit('on-click', !this.currentValue, this.currentValue)
    },
    /**
     * [toBoolean 转化为布尔值]
     * @param  {[type]} val [description]
     * @return {[type]}     [description]
     */
    toBoolean (val) {
      if (!this.valueMap) {
        return val
      } else {
        const index = this.valueMap.indexOf(val)
        return index === 1
      }
    },
    /**
     * [toRaw description]
     * @param  {[type]} val [description]
     * @return {[type]}     [description]
     */
    toRaw (val) {
      if (!this.valueMap) {
        return val
      } else {
        return this.valueMap[val ? 1 : 0]
      }
    }
  },
  data () {
    return {
      currentValue: this.toBoolean(this.value)
    }
  },
  watch: {
    /**
     * [currentValue 监听当前值变化]
     * @param  {[type]} val [description]
     * @return {[type]}     [description]
     */
    currentValue (val) {
      const rawValue = this.toRaw(val)
      this.$emit('input', rawValue)
      this.$emit('on-change', rawValue)
    },
    /**
     * [value 监听外部值变化]
     * @param  {[type]} val [description]
     * @return {[type]}     [description]
     */
    value (val) {
      this.currentValue = this.toBoolean(val)
    }
  }
}
</script>

// lm-angular/src/components/switch/switch.ts
import {
  Input,
  Output,
  ElementRef,
  forwardRef,
  TemplateRef,
  ChangeDetectorRef,
  Component,
  EventEmitter,
  ContentChild,
  OnInit,
  OnChanges,
  OnDestroy,
  SimpleChange,
  SimpleChanges,
  ViewEncapsulation,
  ChangeDetectionStrategy
} from '@angular/core';
// 双响绑定
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { SafeStyle } from '@angular/platform-browser';
import { cleanStyle, replaceVNodeHTMLElement } from '../../core';
import { LmGroupService } from '../group';

interface SwitchProps {
  newVal: any
  oldVal: any	
}

@Component({
  selector: 'lm-switch',
  templateUrl: './switch.html',
  preserveWhitespaces: false,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => LmSwitch),
      multi: true,
    },
  ],
})
export class LmSwitch implements ControlValueAccessor, OnInit, OnChanges  {
  // slot
  @ContentChild('inlineDesc') inlineDescView: TemplateRef<any>
  
  // props
  @Input('name') name: string
  @Input('label') label: string
  @Input('disabled') disabled: boolean
  @Input('borderIntent') borderIntent: boolean
  @Input('inlineDesc') inlineDesc: any
  @Input('preventDefault') preventDefault: boolean
  @Input('valueMap') valueMap: any[]  = [false, true]
  @Input('model') set model(val: boolean | number){
  	this.currentValue = val;
    this.onChange(val);
  }

  // emit
  @Output('on-switch-click') readonly onSwitchClick: EventEmitter<SwitchProps> = new EventEmitter<SwitchProps>(); 
  @Output('input') readonly input: EventEmitter<any> = new EventEmitter<any>(); 
  @Output('on-switch-change') readonly onSwitchChange: EventEmitter<any> = new EventEmitter<any>(); 
  
  // data
  private currentValue: boolean | number
  
  // computed 
  private labelStyle (): SafeStyle {
    // let isHTML: string = /<\/?[^>]*>/.test(this.label)
    // let width = Math.min(isHTML ? 5 : (this.label.length + 1), 14) + 'em'
    return cleanStyle({
      display: 'block',
      // width: this.parent.labelWidth || width,
      width: this.parent.labelWidth,
      textAlign: this.parent.labelAlign
    })
  }
  private labelClass (): object {
    return {
      'lm-cell-justify': this.parent.labelAlign === 'justify'
    }
  }
  private get getBorderIntent (): boolean {
    return (this.parent && this.parent.borderIntent) || this.borderIntent;
  }
  // methods 
  /**
   * [onSwitchClick 点击事件]
   * @return {[type]} [description]
   */
  private onClick(): void {
  	let switchVal: SwitchProps = { 
  	  newVal: !this.currentValue, 
  	  oldVal: this.currentValue 
  	}
    this.onSwitchClick.emit(switchVal)
  }
  /**
   * [toBoolean 转化为布尔值]
   * @param  {[type]} val [description]
   * @return {[type]}     [description]
   */
  private toBoolean (val: any): any {
    if (!this.valueMap) {
      return val
    } else {
      const index = this.valueMap.indexOf(val)
      return index === 1
    }
  }
  /**
   * [toRaw description]
   * @param  {[type]} val [description]
   * @return {[type]}     [description]
   */
  private toRaw (val: any): any {
    if (!this.valueMap) {
      return val
    } else {
      return this.valueMap[val ? 1 : 0]
    }
  }
  // watch
  private changeHandle(value: boolean | number): void {
    this.model = value;
    const rawValue = this.toRaw(value)
    this.input.emit(value)
    this.onSwitchChange.emit(value);
  }

  constructor(
    private el: ElementRef,
  	public parent: LmGroupService, 
  	private cdr: ChangeDetectorRef) {
  }

  ngOnInit() {
    const nativeElement = this.el.nativeElement
    replaceVNodeHTMLElement(nativeElement)
  }

  writeValue(value: boolean | number): void {
    this.model = value;
  }
  // 监听外部更新
  ngOnChanges(changes: SimpleChanges): void {
    
  }
 
  private onChange: Function = () => {}
  private onTouched: Function = () => {}
  // private onTouched: any = Function.prototype;

  registerOnChange(fn: Function): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: Function): void {
    this.onTouched = fn;
  }
}
