// lm-react/examples/views/Grid.tsx
import React from 'react';
import ReactDom from 'react-dom';
import { Component, ComponentProps } from '@src/core'
import { Page, Header, Scroll, Grid } from '@src/index'
//初始化页面

interface GridProps extends ComponentProps {
  match: object
  location: object
  history: object
}
let grids = []
for (let i = 0; i < 9; i++) {
  grids.push({
    'label': 'grid',
    'icon': 'https://www.jzmt168.com/static/images/goods/3fded81b-c84c-463b-92b7-16765fa0b362.jpg'
  })
}
export default class GridPage extends Component<GridProps, any> {
  constructor(props: GridProps) {
    super(props);
  }
  onChange(event) {
    this.setState({
      value: event
    })
  }

  state = {
    value: false
  }

  render() {
    let leftOptions = {
      showBack: false
    }
    let gridLists = [];
    let gridLists2 = [];
    for (let i = 0; i < grids.length; i++) {
      let { label, icon } = grids[i]
      gridLists.push(<Grid.Item key={i} icon={icon} label={label}></Grid.Item>)
      gridLists2.push(<Grid.Item key={i} label={label} iconSlot={<img src={icon} alt="" />}>
      </Grid.Item>)
    }
    return (
      <Page
        header={<Header leftOptions={leftOptions} className={'lm-header-fixed'}>Grid</Header>}>
        <Scroll>
          <Grid>
            {gridLists}
          </Grid>
          <Grid>
            {gridLists2}
          </Grid>
        </Scroll>
      </Page>
    );
  }
}

// lm-vue/examples/views/grid.vue
<template>
  <lm-page>
    <lm-header slot="header" class="lm-header-fixed">九宫格</lm-header>
    <lm-scroll>
      <lm-grid :cols="3">
        <lm-grid-item v-for="(grid, gridIndex) in grids" :key="gridIndex" :label="grid.label" :icon="grid.icon">
        </lm-grid-item>
      </lm-grid>
      <lm-divider>自定义icon</lm-divider>
      <lm-grid :cols="3">
        <lm-grid-item v-for="(grid, gridIndex) in grids" :key="gridIndex" :label="grid.label">
          <img slot="icon" :src="grid.icon" alt="" />
        </lm-grid-item>
      </lm-grid>
    </lm-scroll>
  </lm-page>
</template>

<script>
let grids = []
for (let i = 0; i < 9; i++) {
  grids.push({
    'label': 'grid',
    'icon': 'https://www.jzmt168.com/static/images/goods/3fded81b-c84c-463b-92b7-16765fa0b362.jpg'
  })
}
export default {
  data () {
    return {
      grids: grids
    }
  }
}
</script>

<style lang="scss">
</style>
