// lm-vue/src/components/flexbox/flexbox-item.vue
<template>
  <div class="lm-flexbox-item" :style="style">
    <slot></slot>
  </div>
</template>

<script>
const prefixList = ['-moz-box-', '-webkit-box-', '']
export default {
  name: 'flexbox-item',
  props: {
    span: [Number, String],
    order: [Number, String]
  },
  beforeMount () {
    this.bodyWidth = document.documentElement.offsetWidth
  },
  methods: {
    buildWidth (width) {
      if (typeof width === 'number') {
        if (width < 1) {
          return width
        } else {
          return width / 12
        }
      } else if (typeof width === 'string') {
        return width.replace('px', '') / this.bodyWidth
      }
    }
  },
  computed: {
    style () {
      let styles = {}
      let marginName = this.$parent.orient === 'horizontal' ? 'marginLeft' : 'marginTop'
      if (this.$parent.gutter * 1 !== 0) {
        styles[marginName] = `${this.$parent.gutter}px`
      }
      if (this.span) {
        for (let i = 0; i < prefixList.length; i++) {
          styles[`${prefixList[i]}flex`] = `0 0 ${this.buildWidth(this.span) * 100}%`
        }
      }
      if (typeof this.order !== 'undefined') {
        styles.order = this.order
      }
      return styles
    }
  },
  data () {
    return {
      bodyWidth: 0
    }
  }
}
</script>

// lm-react/src/components/flexbox/FlexboxItem.tsx
import React, { Children } from 'react';
import { Component, View, Transition, Router, pxTorem } from '@src/core';
import { FlexboxItemComponentProps } from './PropsType'
declare let document: any;
const prefixList = ['-moz-box-', '-webkit-box-', '-ms-box-']

interface FlexboxItemProps extends FlexboxItemComponentProps {

};

export class FlexboxItem extends Component<FlexboxItemProps, any> {

  public bodyWidth: number = 0

  static defaultProps: FlexboxItemProps = {

  }

  componentWillMount() {
    this.bodyWidth = document.documentElement.offsetWidth
  }

  constructor(props: FlexboxItemProps) {
    super(props);
  }

  buildWidth(width: number | string): number {
    if (typeof width === 'number') {
      if (width < 1) {
        return width
      } else {
        return width / 12
      }
    } else if (typeof width === 'string' && this.bodyWidth > 0) {
      return Number(width.replace('px', '')) / this.bodyWidth
    }
  }

  get styles() {
    let styles: any = {}
    let { parent, span, order } = this.props;
    let { orient, gutter } = parent
    let marginName = orient === 'horizontal' ? 'marginLeft' : 'marginTop'
    if (gutter * 1 !== 0) {
      styles[marginName] = pxTorem(gutter)
    }
    if (span) {
      for (let i = 0; i < prefixList.length; i++) {
        styles[`${prefixList[i]}flex`] = `0 0 ${this.buildWidth(span) * 100}%`
      }
    }
    if (typeof order !== 'undefined') {
      styles.order = order
    }
    return styles
  }

  render() {
    // let {  } = this.props;
    let styles = this.styles;
    return (
      <div className="lm-flexbox-item" style={styles}>
        {this.props.children}
      </div>
    );
  };
};
