// lm-react/src/components/actionsheet/Actionsheet.tsx
import React from 'react';
import { Component, View, Transition, ComponentProps, isArray, isObject } from '@src/core';
import { Mask } from '../mask';
import { ActionsheetComponentProps, ActionsheetState } from './PropsType'
interface ActionsheetProps extends ActionsheetComponentProps {
  value: boolean
}
export class Actionsheet extends Component<ActionsheetProps, ActionsheetState> {
  state: ActionsheetState = {
    show: false
  }

  static defaultProps: ActionsheetProps = {
    value: false,
    theme: 'ios',
    menus: [],
    maskTransition: 'lm-actionsheet-mask',
    closeOnClickingMask: true,
    closeOnClickingMenu: true
  }

  constructor(props: ActionsheetProps) {
    super(props);

  }
  componentDidMount() {
    let { value } = this.props;
    this.setState({
      show: value || false
    });
  }
  componentWillReceiveProps(nextProps: ActionsheetProps) {
    let { value } = nextProps;
    if (value) {
      this.setState({
        show: value
      })
    }
  }
  onMenuClick(text, key) {
    if (typeof text === 'string') {
      // this.emitEvent('on-click-menu', key, text)
      this.menuHandle(key, text)
    } else {
      if (text.type && (text.type !== 'disabled' && text.type !== 'info')) {
        if (text.value || text.value === 0) {
          this.menuHandle(text.value, text)
        } else {
          this.menuHandle('', text)
        }
      }
    }
    // this.$emit(event, menu, _item)
  }
  menuHandle(item: any, key?: string): void {
    let _item = item;
    let { closeOnClickingMenu, onClickMenu } = this.props
    if (typeof _item === 'object') {
      _item = JSON.parse(JSON.stringify(_item))
    }
    onClickMenu && onClickMenu(_item, key);
    closeOnClickingMenu && this.setState({
      show: false
    })
  }
  // 是否点击遮罩层关闭
  onMaskClick() {
    console.log('onMaskClick')
    let { closeOnClickingMask, onClickMask } = this.props;
    onClickMask && onClickMask();
    closeOnClickingMask && this.setState({
      show: false
    })
  }

  render() {
    let { value, theme, showCancel, cancelText, maskTransition, onHide, maskZIndex, menus, headerSlot } = this.props;
    let { show } = this.state
    return (
      <div className="lm-actionsheet-wrapper">
        <Mask maskZIndex={maskZIndex}
          onMaskClick={() => this.onMaskClick()}
          maskTransition={maskTransition}
          onHide={() => this.props.onHide && this.props.onHide()}
          show={show}>
        </Mask>
        <div className={this.className({
          'lm-skin_android': theme === 'android'
        })}>
          <Transition
            onAfterEnter={() => this.props.onAfterEnter && this.props.onAfterEnter()}
            onAfterLeave={() => this.props.onAfterLeave && this.props.onAfterLeave()}
            name={theme === 'android' ? 'lm-android-actionsheet' : 'lm-ios-actionsheet'}>
            <View show={show}>
              {
                (theme === 'android') ? (
                  <div className="lm-actionsheet">
                    <div className="lm-actionsheet-menu">
                      {
                        isArray(menus) ? (
                          menus && (menus as any).map((item, index) => {
                            return (
                              <div key={index} className="lm-actionsheet-cell"
                                onClick={() => this.onMenuClick(item, index)}>{item.label || item}</div>
                            )
                          })
                        ) : (
                            Object.keys(menus).map((item, index) => {
                              return (
                                <div
                                  key={item}
                                  className="lm-actionsheet-cell"
                                  onClick={() => this.onMenuClick(menus[item], item)}>{menus[item].label || menus[item]}</div>
                              )
                            })
                          )
                      }

                    </div>
                  </div>
                ) : (
                    <div className={this.className('lm-actionsheet lm-ios-actionsheet')}
                      ref="iOSMenu">
                      <div className="lm-actionsheet-menu">
                        {
                          headerSlot ? (
                            { headerSlot }
                          ) : (null)
                        }
                        {
                          isArray(menus) ? (
                            menus && (menus as any).map((item, index) => {
                              return (
                                <div
                                  key={index}
                                  data-key={index}
                                  className={this.className('lm-actionsheet-cell', `lm-actionsheet-menu-${item.type || 'default'}`)}
                                  onClick={() => this.onMenuClick(item, index)}>
                                  {item.label || item}
                                </div>
                              )
                            })
                          ) : (
                              Object.keys(menus).map((item, index) => {
                                return (
                                  <div
                                    key={item}
                                    data-key={item}
                                    className={this.className('lm-actionsheet-cell', `lm-actionsheet-menu-${menus[item].type || 'default'}`)}
                                    onClick={() => this.onMenuClick(menus[item], item)}>
                                    {menus[item].label || menus[item]}
                                  </div>
                                )
                              })
                            )

                        }
                      </div>
                      {
                        showCancel ? (
                          <div className="lm-actionsheet-action"
                            onClick={() => this.menuHandle('cancel')}
                          >
                            <div className="lm-actionsheet-cell">{cancelText || '取消'}</div>
                          </div>
                        ) : (null)
                      }
                    </div>
                  )
              }
            </View>
          </Transition>
        </div>
      </div>
    );
  };
};

// lm-vue/src/components/actionsheet/actionsheet.vue
<template>
  <div class="lm-actionsheet-wrapper">
    <transition name="lm-actionsheet-mask">
      <div
        class="lm-mask lm-mask-transparent"
        @click="onClickingMask"
        v-show="show"></div>
    </transition>
    <div
      class="lm-skin_android"
      v-if="theme === 'android'">
      <transition
        name="lm-android-actionsheet"
        @after-enter="$emit('on-after-show')"
        @after-leave="$emit('on-after-hide')">
        <div
          class="lm-actionsheet"
          v-show="show">
          <div class="lm-actionsheet-menu">
            <div
              class="lm-actionsheet-cell"
              v-for="(text, key) in menus"
              :key="key"
              @click="onMenuClick(text, key)"
              v-html="text.label || text">
            </div>
          </div>
        </div>
      </transition>
    </div>
    <div
      class="lm-actionsheet"
      :class="{'lm-actionsheet_toggle': show}"
      v-else
      ref="iOSMenu">
      <div class="lm-actionsheet-menu">
        <div class="lm-actionsheet-cell" v-if="hasHeaderSlot">
          <slot name="header"></slot>
        </div>
        <div class="lm-actionsheet-cell"
          v-for="(text, key) in menus"
          :key="key"
          :data-key="key"
          @click="onMenuClick(text, key)"
          v-html="text.label || text"
          :class="`lm-actionsheet-menu-${text.type || 'default'}`">
        </div>
      </div>
      <div
        class="lm-actionsheet-action"
        @click="emitEvent('on-click-menu', 'cancel')"
        v-if="showCancel">
        <div class="lm-actionsheet-cell">{{ cancelText || '取消' }}</div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  name: 'lm-actionsheet',
  mounted () {
    this.hasHeaderSlot = !!this.$slots.header
    this.$nextTick(() => {
      this.$tabbar = document.querySelector('.lm-tabbar')
      this.$refs.iOSMenu && this.$refs.iOSMenu.addEventListener('transitionend', this.onTransitionEnd)
    })
  },
  props: {
    value: Boolean,
    showCancel: Boolean,
    cancelText: String,
    theme: {
      type: String,
      default: 'ios'
    },
    menus: {
      type: [Object, Array],
      default: () => ({})
    },
    closeOnClickingMask: {
      type: Boolean,
      default: true
    },
    closeOnClickingMenu: {
      type: Boolean,
      default: true
    }
  },
  data () {
    return {
      hasHeaderSlot: false,
      show: false
    }
  },
  methods: {
    onTransitionEnd () {
      this.$emit(this.show ? 'on-after-show' : 'on-after-hide')
    },
    onMenuClick (text, key) {
      console.log(text, '---', key, this.menus, 'text, key')
      if (typeof text === 'string') {
        this.emitEvent('on-click-menu', key, text)
      } else {
        if (text.type !== 'disabled' && text.type !== 'info') {
          if (text.value || text.value === 0) {
            this.emitEvent('on-click-menu', text.value, text)
          } else {
            this.emitEvent('on-click-menu', '', text)
            this.show = false
          }
        }
      }
    },
    onClickingMask () {
      this.$emit('on-click-mask')
      this.closeOnClickingMask && (this.show = false)
    },
    emitEvent (event, menu, item) {
      if (event === 'on-click-menu' && !/.noop/.test(menu)) {
        let _item = item
        if (typeof _item === 'object') {
          _item = JSON.parse(JSON.stringify(_item))
        }
        this.$emit(event, menu, _item)
        this.$emit(`${event}-${menu}`)
        this.closeOnClickingMenu && (this.show = false)
      }
    },
    fixIos (zIndex) {
      if (this.$el.parentNode && this.$el.parentNode.className.indexOf('v-transfer-dom') !== -1) {
        return
      }
      if (this.$tabbar && /iphone/i.test(navigator.userAgent)) {
        this.$tabbar.style.zIndex = zIndex
      }
    }
  },
  watch: {
    show (val) {
      this.$emit('input', val)
      if (val) {
        this.fixIos(-1)
      } else {
        setTimeout(() => {
          this.fixIos(100)
        }, 200)
      }
    },
    value: {
      handler: function (val) {
        this.show = val
      },
      immediate: true
    }
  },
  beforeDestroy () {
    this.fixIos(100)
    this.$refs.iOSMenu && this.$refs.iOSMenu.removeEventListener('transitionend', this.onTransitionEnd)
  }
}
</script>
