// lm-react/src/components/switch/Switch.tsx
import React from 'react';
import { Component, ComponentProps, pxTorem, cleanStyle, isEqual } from '@src/core';
import { Header } from '../header/index';
import { InlineDesc } from '../inline-desc'
import { SwitchComponentProps, SwitchState } from './PropsType'

interface SwitchProps extends SwitchComponentProps {

}

export class Switch extends Component<SwitchProps, SwitchState> {

  wrap: any

  state: SwitchState = {
    currentValue: false
  }

  static defaultProps: SwitchProps = {
    value: false,
    valueMap: [false, true]
  }

  constructor(props: SwitchProps) {
    super(props);
    this.state = {
      currentValue: this.toBoolean(props.value ? props.value : false)
    }
  }

  toBoolean(val) {
    let { valueMap } = this.props
    if (!valueMap) {
      return val
    } else {
      const index = valueMap.indexOf(val)
      return index === 1
    }
  }
  toRaw(val) {
    let { valueMap } = this.props
    if (!valueMap) {
      return val
    } else {
      return valueMap[val ? 1 : 0]
    }
  }

  componentWillReceiveProps(nextProps: SwitchProps) {
    let { value } = nextProps;
    let { currentValue } = this.state
    if (!isEqual(value, currentValue)) {
      this.setState({
        currentValue: this.toBoolean(value)
      });
    }
  }

  get labelStyle() {
    let { switchLabel, parent } = this.props;
    let { labelWidth, labelAlign } = parent;
    let isHTML = /<\/?[^>]*>/.test(switchLabel);
    let width = Math.min(isHTML ? 5 : (switchLabel && switchLabel.length + 1), 14) + 'em'
    return cleanStyle({
      display: 'block',
      width: labelWidth || width,
      textAlign: labelAlign
    })
  }

  get labelClass() {
    let { parent } = this.props;
    let { labelAlign } = parent
    return {
      'lm-cell-justify': labelAlign === 'justify'
    }
  }
  handleInputChange(event: any) {
    // 获取绑定的枚举值
    const checked = this.toRaw(event.target.checked);
    let { input, onChange } = this.props;
    this.setState({
      currentValue: checked
    });
    input && input(checked);
    onChange && onChange(checked);
  }

  render() {
    const {
      switchLabel,
      disabled,
      value,
      inlineDesc,
      preventDefault,
      valueMap
    } = this.props;
    let labelStyle = this.labelStyle;
    let labelClass = this.labelClass;

    let { currentValue } = this.state;

    return (
      <div className={this.className('lm-switch-wrapper lm-cell lm-cell-switch')}>
        <div className={this.className('lm-cell-bd')}>
          <label className={this.className('lm-label', labelClass)}
            style={this.style(labelStyle)}>{switchLabel}</label>
          {
            inlineDesc ? (<InlineDesc>{inlineDesc}</InlineDesc>) : (null)
          }
        </div>
        <div className={this.className('lm-cell-switch-body')}>
          <input
            className="lm-switch"
            type="checkbox"
            disabled={disabled}
            checked={currentValue}
            onChange={(e) => this.handleInputChange(e)}
          />

          {
            preventDefault ? (<div className="lm-switch-overlay"></div>) : (null)
          }
        </div>
      </div>
    );
  };
};

// lm-vue/src/components/switch/switch.vue
<template>
  <div class="lm-switch-wrapper lm-cell lm-cell-switch">
    <div class="lm-cell-bd">
      <label class="lm-label" :style="labelStyle" :class="labelClass" v-html="label"></label>
      <inline-desc v-if="inlineDesc">{{ inlineDesc }}</inline-desc>
    </div>
    <div class="lm-cell-switch-body">
      <input class="lm-switch" type="checkbox" :disabled="disabled" v-model="currentValue" />
      <div v-if="preventDefault" class="lm-switch-overlay" @click="onClick"></div>
    </div>
  </div>
</template>

<script>
import InlineDesc from '../inline-desc/inline-desc'
import { cleanStyle } from '@/utils'
export default {
  name: 'lm-switch',
  props: {
    label: {
      type: String,
      required: true
    },
    disabled: Boolean,
    value: {
      type: [Boolean, String, Number],
      default: false,
      required: true
    },
    inlineDesc: [String, Boolean, Number],
    preventDefault: Boolean,
    valueMap: {
      type: Array,
      default: () => ([false, true])
    }
  },
  computed: {
    parent () {
      const { $parent } = this
      return $parent || {}
    },
    labelStyle () {
      let isHTML = /<\/?[^>]*>/.test(this.label)
      let width = Math.min(isHTML ? 5 : (this.label.length + 1), 14) + 'em'
      return cleanStyle({
        display: 'block',
        width: this.parent.labelWidth || width,
        textAlign: this.parent.labelAlign
      })
    },
    labelClass () {
      return {
        'lm-cell-justify': this.parent.labelAlign === 'justify'
      }
    }
  },
  components: {
    InlineDesc
  },
  methods: {
    /**
     * [onClick 点击事件]
     * @return {[type]} [description]
     */
    onClick () {
      this.$emit('on-click', !this.currentValue, this.currentValue)
    },
    /**
     * [toBoolean 转化为布尔值]
     * @param  {[type]} val [description]
     * @return {[type]}     [description]
     */
    toBoolean (val) {
      if (!this.valueMap) {
        return val
      } else {
        const index = this.valueMap.indexOf(val)
        return index === 1
      }
    },
    /**
     * [toRaw description]
     * @param  {[type]} val [description]
     * @return {[type]}     [description]
     */
    toRaw (val) {
      if (!this.valueMap) {
        return val
      } else {
        return this.valueMap[val ? 1 : 0]
      }
    }
  },
  data () {
    return {
      currentValue: this.toBoolean(this.value)
    }
  },
  watch: {
    /**
     * [currentValue 监听当前值变化]
     * @param  {[type]} val [description]
     * @return {[type]}     [description]
     */
    currentValue (val) {
      const rawValue = this.toRaw(val)
      this.$emit('input', rawValue)
      this.$emit('on-change', rawValue)
    },
    /**
     * [value 监听外部值变化]
     * @param  {[type]} val [description]
     * @return {[type]}     [description]
     */
    value (val) {
      this.currentValue = this.toBoolean(val)
    }
  }
}
</script>
