// lm-vue/src/components/group/group-title.vue
<template>
  <div class="lm-form-preview-header">
    <slot>
      <slot name="header-left">
        <label class="lm-form-preview-label" v-html="headerLabel"></label>
      </slot>
      <slot name="header-right">
        <span class="lm-form-preview-value" v-html="headerValue || '&nbsp;'"></span>
      </slot>
    </slot>
  </div>
</template>
<script>
export default {
  name: 'group-title',
  props: {
    headerLabel: String,
    headerValue: String,
    previewItems: Array
  }
};
</script>

// lm-react/src/components/group/GroupTitle.tsx
import React from 'react';
import { Component, ComponentProps } from '@src/core';

interface GroupTitleProps extends ComponentProps {
  headerLabel: string
  headerValue: string
};

export default class GroupTitle extends Component<GroupTitleProps, any> {

  constructor(props: GroupTitleProps) {
    super(props);
  }

  render() {
    let { children, headerValue, headerLabel } = this.props;
    return (
      <div className={this.className('lm-form-preview-header')}>
        {
          (headerValue || headerLabel) ? (
            <React.Fragment>
              <label className={this.className('lm-form-preview-label')}>{headerLabel}</label>
              <span className={this.className('lm-form-preview-value')}>{headerValue}</span>
            </React.Fragment>
          ) : (<React.Fragment>{children}</React.Fragment>)
        }
      </div>
    );
  };
};
