// lm-vue/examples/views/grid.vue
<template>
  <lm-page>
    <lm-header slot="header" class="lm-header-fixed">九宫格</lm-header>
    <lm-scroll>
      <lm-grid :cols="3">
        <lm-grid-item v-for="(grid, gridIndex) in grids" :key="gridIndex" :label="grid.label" :icon="grid.icon">
        </lm-grid-item>
      </lm-grid>
      <lm-divider>自定义icon</lm-divider>
      <lm-grid :cols="3">
        <lm-grid-item v-for="(grid, gridIndex) in grids" :key="gridIndex" :label="grid.label">
          <img slot="icon" :src="grid.icon" alt="" />
        </lm-grid-item>
      </lm-grid>
    </lm-scroll>
  </lm-page>
</template>

<script>
let grids = []
for (let i = 0; i < 9; i++) {
  grids.push({
    'label': 'grid',
    'icon': 'https://www.jzmt168.com/static/images/goods/3fded81b-c84c-463b-92b7-16765fa0b362.jpg'
  })
}
export default {
  data () {
    return {
      grids: grids
    }
  }
}
</script>

<style lang="scss">
</style>

// lm-angular/examples/app/views/grid/grid.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'grid-page',
  templateUrl: './grid.component.html',
  styleUrls: ['./grid.component.scss']
})
export class GridComponent {
  title = 'lm-angular-grid';
  onClickMoreHandle () {
  	console.log('onClickMoreHandle')
  }
  fours: any[] = []
  items: any[] = [1, 2, 3, 4, 5]
}

<lm-template>
  <ng-template #header>
  	<lm-header  class="lm-header-fixed" [left-options]="{ showBack: false }" [right-options]="{ showMore: false }">
  	  <ng-template #navbarTitle>{{ title }}</ng-template>
  	  <ng-template #navbarRight>
  	  	<div (click)="onClickMoreHandle()">right</div>
  	  </ng-template>	
  	</lm-header>
  </ng-template>
  <br />
  <lm-grid [cols]="4" [showLrBorders]="false" [showVerticalDividers]="false">
    <lm-grid-item [icon]="'https://www.jzmt168.com/static/images/goods/3fded81b-c84c-463b-92b7-16765fa0b362.jpg'" [link]="['home', item]" [param]="{ queryParams: { id:  item  } }" *ngFor="let item of items"  [label]="item"></lm-grid-item>
  </lm-grid>
  <br />
  <lm-grid [cols]="4">
    <lm-grid-item [link]="['home', item]" [param]="{ queryParams: { id:  item  } }" *ngFor="let item of items"  [label]="item">
      <ng-template #gridIcon>
        <img src="https://www.jzmt168.com/static/images/goods/3fded81b-c84c-463b-92b7-16765fa0b362.jpg" />
      </ng-template>
    </lm-grid-item>
  </lm-grid>
</lm-template>
