// lm-vue/src/components/dialog/dialog.vue
<template>
  <div
    class="lm-dialog-wrapper"
    :class="{'lm-dialog-absolute': layout === 'PAGE_VIEW'}">
    <transition :name="maskTransition">
      <div class="lm-mask" @click="hide" v-show="show" :style="maskStyle"></div>
    </transition>
    <transition :name="dialogTransition">
      <div :class="dialogClass" v-show="show" :style="dialogStyle">
        <slot></slot>
      </div>
    </transition>
  </div>
</template>

<script>
import { preventBodyScrollMixin } from '@/mixins'
export default {
  name: 'lm-dialog',
  mixins: [preventBodyScrollMixin],
  model: {
    prop: 'show',
    event: 'change'
  },
  props: {
    show: {
      type: Boolean,
      default: false
    },
    maskTransition: {
      type: String,
      default: 'lm-mask'
    },
    maskZIndex: [String, Number],
    dialogTransition: {
      type: String,
      default: 'lm-dialog'
    },
    dialogClass: {
      type: String,
      default: 'lm-dialog'
    },
    hideOnBlur: Boolean,
    dialogStyle: Object,
    scroll: {
      type: Boolean,
      default: true,
      validator (val) {
        /* istanbul ignore if */
        if (process.env.NODE_ENV === 'development' && val === false) {
          console.warn('[VUX warn] x-dialog:scroll 已经废弃。如果你是 100% 布局，请参照文档配置 $layout 以实现阻止滚动')
        }
        return true
      }
    }
  },
  computed: {
    maskStyle () {
      if (typeof this.maskZIndex !== 'undefined') {
        return {
          zIndex: this.maskZIndex
        }
      }
    }
  },
  mounted () {
    if (typeof window !== 'undefined') {
      if (window.LM_CONFIG && window.LM_CONFIG.$layout === 'PAGE_VIEW') {
        this.layout = 'PAGE_VIEW'
      }
    }
  },
  watch: {
    show (val) {
      this.$emit('update:show', val)
      this.$emit(val ? 'on-show' : 'on-hide')
      if (val) {
        this.addModalClassName()
      } else {
        this.removeModalClassName()
      }
    }
  },
  methods: {
    shouldPreventScroll () {
      // hard to get focus on iOS device with fixed position, so just ignore it
      const iOS = /iPad|iPhone|iPod/i.test(window.navigator.userAgent)
      const hasInput = this.$el.querySelector('input') || this.$el.querySelector('textarea')
      if (iOS && hasInput) {
        return true
      }
    },
    hide () {
      if (this.hideOnBlur) {
        this.$emit('update:show', false)
        this.$emit('change', false)
        this.$emit('on-click-mask')
      }
    }
  },
  data () {
    return {
      layout: ''
    }
  }
}
</script>

// lm-angular/src/components/dialog/dialog.ts
import {
  Input,
  Output,
  forwardRef,
  TemplateRef,
  ChangeDetectorRef,
  Component,
  EventEmitter,
  ContentChild,
  ElementRef,
  OnInit,
  OnDestroy,
  SimpleChange,
  SimpleChanges,
  ViewEncapsulation,
  ChangeDetectionStrategy
} from '@angular/core';
// 双响绑定
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { SafeStyle } from '@angular/platform-browser';
import { 
  cleanStyle,
  querySelector,
  DialogAnimation,
  MaskAnimation 
} from '../../core';

@Component({
  selector: 'lm-dialog',
  templateUrl: './dialog.html',
  preserveWhitespaces: false,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  animations: [DialogAnimation, MaskAnimation],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => LmDialog),
      multi: true,
    },
  ],
})
export class LmDialog implements ControlValueAccessor {
  // slot

  // props
  @Input('model') set model(val: boolean){
  	this.currentValue = val;
    this.controlChange(val);
  }
  @Input('mask-transition') maskTransition: string = 'lm-mask'
  @Input('mask-z-index') maskZIndex: string | number
  @Input('dialog-transition') dialogTransition: string = 'lm-dialog'
  @Input('dialog-class') dialogClass: string = 'lm-dialog'
  @Input('hide-on-blur') hideOnBlur: boolean
  @Input('dialog-style') dialogStyle: object
  @Input('is-scroll') isScroll: boolean = true


  // emit
  @Output('on-click-mask') readonly onClickMask: EventEmitter<any> = new EventEmitter<any>(); 
  @Output('on-change') readonly onChange: EventEmitter<boolean> = new EventEmitter<boolean>(); 
  @Output('on-show') readonly onShow: EventEmitter<boolean> = new EventEmitter<boolean>(); 
  @Output('on-hide') readonly onHide: EventEmitter<boolean> = new EventEmitter<boolean>(); 
  
  // data
  private currentValue: boolean = false
  private layout: string = '' 

  // methods
  // 关闭弹窗
  public hideHandle () {
    if (this.hideOnBlur) {
      this.changeHandle(false);
      this.onClickMask.emit();
    }
  }

  private shouldPreventScroll (): boolean {
    // hard to get focus on iOS device with fixed position, so just ignore it
    const iOS = /iPad|iPhone|iPod/i.test(window.navigator.userAgent)
    // const hasInput = querySelector('input', this.el) || querySelector('textarea', this.el);
    if (iOS) {
      return true
    }
    return false;
  }

  //
  private changeHandle(value: boolean): void {
    this.model = value;
    value ? this.onShow.emit(value) : this.onHide.emit(value)
  }

  // computed
  private maskStyle (): any {
    if (typeof this.maskZIndex !== 'undefined') {
      return {
        zIndex: this.maskZIndex
      }
    }
  }

  constructor(
    private el: ElementRef, 
  	private cdr: ChangeDetectorRef) {
  }
  
  // 下面是数据双向绑定
  writeValue(value: boolean): void {
    this.model = value;
  }
  
  private controlChange: Function = () => {}
  private controlTouch: Function = () => {}
  // private onTouched: any = Function.prototype;

  registerOnChange(fn: Function): void {
    this.controlChange = fn;
  }

  registerOnTouched(fn: Function): void {
    this.controlTouch = fn;
  }
}
