// lm-vue/src/components/address/address.vue
<template>
  <popup-picker
    :fixed-columns="hideDistrict ? 2 : 0"
    :columns="3"
    :data="list"
    :label="label"
    v-model="currentValue"
    show-name
    :inline-desc="inlineDesc"
    :placeholder="placeholder"
    :value-text-align="valueTextAlign"
    :confirm-text="confirmText"
    :cancel-text="cancelText"
    :display-format="displayFormat"
    :popup-style="popupStyle"
    :popup-title="popupTitle"
    :show.sync="showValue"
    :disabled="disabled"
    @on-shadow-change="onShadowChange"
    @on-hide="emitHide"
    @on-show="$emit('on-show')">
    <template slot="title" slot-scope="props">
      <slot
        name="title"
        :label-class="props.labelClass"
        :label-style="props.labelStyles"
        :label-title="props.title">
        <label
          :class="[props.labelClass,labelClass]"
          :style="props.labelStyle"
          v-if="props.labelTitle"
          v-html="props.labelTitle"></label>
      </slot>
    </template>
  </popup-picker>
</template>

<script>
import name2value from '@/filters/name2value'
import value2name from '@/filters/value2name'
import PopupPicker from '../popup-picker/popup-picker'
export default {
  name: 'lm-address',
  components: {
    PopupPicker
  },
  props: {
    label: {
      type: String,
      required: true
    },
    value: {
      type: Array,
      default () {
        return []
      }
    },
    rawValue: Boolean,
    list: {
      type: Array,
      required: true
    },
    labelWidth: String,
    inlineDesc: String,
    placeholder: String,
    hideDistrict: Boolean,
    valueTextAlign: String,
    confirmText: String,
    cancelText: String,
    displayFormat: {
      type: Function,
      default: (val, names) => names
    },
    popupStyle: Object,
    popupTitle: String,
    show: Boolean,
    disabled: Boolean
  },
  created () {
    if (this.currentValue.length && this.rawValue) {
      const parsedVal = name2value(this.currentValue, this.list)
      if (/__/.test(parsedVal)) {
        console.error('[VUX] Wrong address value', this.currentValue)
        this.currentValue = [];
      } else {
        this.currentValue = parsedVal.split(' ')
      }
    }
    if (this.show) {
      this.showValue = true
    }
  },
  methods: {
    emitHide (val) {
      this.$emit('on-hide', val)
    },
    getAddressName () {
      return value2name(this.value, this.list)
    },
    onShadowChange (ids, names) {
      this.$emit('on-shadow-change', ids, names)
    }
  },
  data () {
    return {
      currentValue: this.value,
      showValue: false
    }
  },
  computed: {
    nameValue () {
      return value2name(this.currentValue, this.list)
    },
    labelClass () {
      return {
        'lm-cell-justify': this.$parent && (this.$parent.labelAlign === 'justify' || this.$parent.$parent.labelAlign === 'justify')
      }
    }
  },
  watch: {
    currentValue (val) {
      this.$emit('input', val)
    },
    value (val) {
      if (val.length && !/\d+/.test(val[0])) {
        const id = name2value(val, this.list).split(' ')
        if (id[0] !== '__' && id[1] !== '__') {
          this.currentValue = id
          return
        }
      }
      this.currentValue = val
    },
    show (val) {
      this.showValue = val
    },
    showValue (val) {
      this.$emit('update:show', val)
    }
  }
}
</script>

// lm-angular/src/components/address/address.ts
import {
  Input,
  Output,
  forwardRef,
  TemplateRef,
  ChangeDetectorRef,
  Component,
  EventEmitter,
  ContentChild,
  OnInit,
  DoCheck,
  OnChanges,
  OnDestroy,
  SimpleChange,
  SimpleChanges,
  ViewEncapsulation,
  ChangeDetectionStrategy
} from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { Observable, Observer, Subscription } from 'rxjs';
import { SafeStyle } from '@angular/platform-browser';
import { extend, isEqual } from '../../core'
import { name2value, value2name } from '../../filters'
import { LmGroupService } from '../group'
@Component({
  selector: 'lm-address',
  templateUrl: './address.html',
  preserveWhitespaces: false,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => LmAddress),
      multi: true,
    },
  ],
})
export class LmAddress implements ControlValueAccessor, OnInit, OnChanges {
  // slot 插槽视图
  @Input('label') label: string
  
  @Input('model') set model(value: any[]) {
    if (value && !isEqual(value, this.currentValue)) {
      this.setCurrentValue(value)
    }
  }
  get model(): any[] {
    return this.currentValue;
  }
  @Input('rawValue') rawValue: boolean
  
  @Input('data') data: any[] = []
  
  @Input('label-width') labelWidth: string

  @Input('inline-desc') inlineDesc: string
  
  @Input('placeholder') placeholder: string 
  
  @Input('hide-district') hideDistrict: boolean  
  
  @Input('value-text-align') valueTextAlign: string 
  
  @Input('confirm-text') confirmText: string = '完成'
  
  @Input('cancel-text') cancelText: string = '取消'
  
  @Input('display-format') displayFormat: Function = (val, names) => names
  
  @Input('popup-style') popupStyle: object
  
  @Input('popup-title') popupTitle: string

  @Input('show') set show(value: boolean) {
    if (value && !isEqual(value, this.showValue)) {
      this.showValue = value;
    } 
  } 
  get show(): boolean {
    return this.showValue;
  }

  @Input('disabled') disabled: boolean  
  
  // emit
  @Output('input') input: EventEmitter<any> = new EventEmitter<any>(); 
  @Output('on-change') onChange: EventEmitter<any> = new EventEmitter<any>(); 
  @Output('on-show') onShow: EventEmitter<any> = new EventEmitter<any>(); 
  @Output('on-hide') onHide: EventEmitter<any> = new EventEmitter<any>(); 
  @Output('on-shadow-change') onShadowChange: EventEmitter<any> = new EventEmitter<any>(); 
  
  private currentValue: any[] = []
  private showValue: boolean = false

  nameValue () {
    return value2name(this.currentValue, this.data)
  }

  labelClass () {
    return {
      'lm-cell-justify': this.parent && this.parent.labelAlign === 'justify'
    }
  }
  
  _onHide ($event) {
    this.onHide.emit($event)
  }
   
  _onShow ($event) {
    this.onShow.emit($event);
  }
   
  getAddressName () {
    console.log(this.currentValue, 'this.currentValue')
    return value2name(this.currentValue, this.data)
  }
   
  onShadowChangeHandle ($event) {
    this.onShadowChange.emit($event)
  }
  
  constructor(
    private cdr: ChangeDetectorRef,
    private parent: LmGroupService) {
  }

  ngOnInit () {
    if (this.currentValue.length && this.rawValue) {
      const parsedVal = name2value(this.currentValue, this.data)
      if (/__/.test(parsedVal)) {
        this.currentValue = [];
      } else {
        this.currentValue = parsedVal.split(' ')
      }
    }
  }
  // 设置绑定数据
  setCurrentValue(val): void {
    if (val.length && !/\d+/.test(val[0])) {
      const id = name2value(val, this.data).split(' ')
      if (id[0] !== '__' && id[1] !== '__') {
        this.currentValue = id;
      }
    } else {
      this.currentValue = val || [];
    }
    this.cdr.markForCheck();
    this.cdr.detectChanges();
  }
  // 下面是数据双向绑定
  writeValue(value: any): void {
    this.currentValue = value;
    if (value && !isEqual(value, this.currentValue)) {
      this.setCurrentValue(value)
    }
  }
  ngOnChanges(changes: SimpleChanges) {
    let { model, show } = changes;
    if (typeof model !== 'undefined' && !isEqual(model.currentValue, this.model)) {
      this.setCurrentValue(model.currentValue)
    }
    if (typeof show !== 'undefined' && !isEqual(show.currentValue, this.show)) {
      this.showValue = show.currentValue
    }
  }
  private controlChange: Function = () => {}
  private controlTouch: Function = () => {}
  // private onTouched: any = Function.prototype;
  
  registerOnChange(fn: Function): void {
    this.controlChange = fn;
  }

  registerOnTouched(fn: Function): void {
    this.controlTouch = fn;
  }

  ngOnDestroy(): void {
    
  }
}
