// lm-vue/examples/views/flexbox.vue
<template>
  <lm-page>
    <lm-header>flexbox</lm-header>
    <lm-flexbox>
      <lm-flexbox-item><div class="flex-demo">1</div></lm-flexbox-item>
      <lm-flexbox-item><div class="flex-demo">2</div></lm-flexbox-item>
    </lm-flexbox>

    <lm-flexbox :gutter="0">
      <lm-flexbox-item><div class="flex-demo">1</div></lm-flexbox-item>
      <lm-flexbox-item><div class="flex-demo">2</div></lm-flexbox-item>
      <lm-flexbox-item><div class="flex-demo">3</div></lm-flexbox-item>
      <lm-flexbox-item><div class="flex-demo">4</div></lm-flexbox-item>
      <lm-flexbox-item><div class="flex-demo">5</div></lm-flexbox-item>
      <lm-flexbox-item><div class="flex-demo">6</div></lm-flexbox-item>
    </lm-flexbox>
  </lm-page>
</template>

<script>
export default {
  data () {
    return {
      value: false
    }
  }
}
</script>
<style lang="scss">

</style>

// lm-angular/examples/app/views/flexbox/flexbox.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'flexbox-page',
  templateUrl: './flexbox.component.html',
  styleUrls: ['./flexbox.component.scss']
})
export class FlexboxComponent {
  title = 'lm-angular-demo';
}

<lm-template>
  <ng-template #header>
  	<lm-header  class="lm-header-fixed" [left-options]="{ showBack: false }" [right-options]="{ showMore: false }">
  	  <ng-template #navbarTitle>{{ title }}</ng-template>
  	  <ng-template #navbarRight>
  	  	<div (click)="onClickMoreHandle()">right</div>
  	  </ng-template>	
  	</lm-header>
  </ng-template>
  <lm-flexbox>
    <lm-flexbox-item><div class="flex-demo">内容</div></lm-flexbox-item>
    <lm-flexbox-item><div class="flex-demo">内容</div></lm-flexbox-item>
    <lm-flexbox-item><div class="flex-demo">内容</div></lm-flexbox-item>
    <lm-flexbox-item><div class="flex-demo">内容</div></lm-flexbox-item>
  </lm-flexbox> 
</lm-template>
